CREATE OR REPLACE PROCEDURE VERCENTRO(P_ID CENTROTRABAJO.ID%TYPE) IS 
NO_ENCONTRADO EXCEPTION;
  CURSOR C_CENT IS
SELECT C.ID, C.NOMBRE CNOM, C.CALLE, C.NUMERO, C.COD_POSTAL, C.CIUDAD, C.PROVINCIA, C.TELEFONO, T.DNI
FROM TRABAJADOR T, CENTROTRABAJO C
WHERE T.ID = C.ID AND C.ID = P_ID;
  CENT_RECORDS C_CENT%ROWTYPE;
BEGIN
  OPEN C_CENT;
  IF SQL%NOTFOUND
  THEN RAISE NO_ENCONTRADO;
  ELSE FETCH C_CENT INTO CENT_RECORDS;
  END IF;
END;