CREATE OR REPLACE PROCEDURE VERTRABAJADOR(P_DNI TRABAJADOR.DNI%TYPE) IS 
NO_ENCONTRADO EXCEPTION;
  CURSOR C_TRAB IS
SELECT T.DNI, T.NOMBRE NOM, T.APELLIDO1, T.APELLIDO2, T.CALLE, T.PORTAL, T.PISO, T.MANO, T.TEL_EMPRESA, T.TEL_PERSONAL, T.FECHA_NAC, T.SALARIO,C.NOMBRE ,C.ID
FROM TRABAJADOR T, CENTROTRABAJO C
WHERE T.ID = C.ID AND T.DNI = P_DNI;
  TRAB_RECORDs C_TRAB%ROWTYPE;
BEGIN
  OPEN C_TRAB;
  IF SQL%NOTFOUND
  THEN RAISE NO_ENCONTRADO;
  ELSE FETCH C_TRAB INTO TRAB_RECORDs;
  END IF;
END;

EXEC VERTRABAJADOR('11812853F');
